[package]
name = "sgdktool"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "6.0.0"
toml_edit = "0.22.27"
which = "8.0.0"
fs_extra = "1.3"
reqwest = { version = "0.12.20", features = ["blocking", "json"] }
rust-i18n = "3"
zip = "4.1.0"
tempfile = "3.8"
sevenz-rust = "0.6.1"
regex = "1"
dialoguer = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "8"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
mime_guess = "2"
